name: mi_card
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_svg: ^0.22.0
  shared_preferences: ^2.0.5
  fluttertoast: ^8.0.6
  provider: ^5.0.0
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  path_provider: ^2.0.1
  image_picker: ^0.7.5
  #location: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  hive_generator:

flutter:
  uses-material-design: true
  assets:
    - assets/buttons/
    - assets/icons/
  fonts:
    - family: Newsreader
      fonts:
        - asset: assets/fonts/Newsreader-Italic-VariableFont_opsz,wght.ttf
        - asset: assets/fonts/Newsreader-VariableFont_opsz,wght.ttf
          style: italic
